sudo: true

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - cache

env:
  - IMAGINE_DRIVER=imagick
  - IMAGINE_DRIVER=gmagick

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - sudo apt-get update
  - sudo apt-get remove -y imagemagick libmagickcore-dev libmagickwand-dev
  - sudo apt-get update -y || true
  - sudo apt-get install -y ca-certificates libtiff-dev libjpeg-dev libdjvulibre-dev libwmf-dev pkg-config liblcms2-dev
  - PHPUNIT_EXCLUDED_GROUPS=none
  - if test "${IMAGINE_DRIVER}" = 'imagick'; then ./.travis/imagick.sh; else PHPUNIT_EXCLUDED_GROUPS="${PHPUNIT_EXCLUDED_GROUPS},ext-imagick"; fi
  - if test "${IMAGINE_DRIVER}" = 'gmagick'; then ./.travis/gmagick.sh; else PHPUNIT_EXCLUDED_GROUPS="${PHPUNIT_EXCLUDED_GROUPS},ext-gmagick"; fi
  - php --ri curl || true
  - composer install

script:
  - composer test -- --exclude-group "${PHPUNIT_EXCLUDED_GROUPS}"

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly
  include:
    - php: 5.3
      dist: precise
      env:
        - IMAGINE_DRIVER=imagick
    - php: 5.3
      dist: precise
      env:
        - IMAGINE_DRIVER=gmagick
